[tools]
python = "3.13"
uv = "latest"

[tasks.check]
depends = ["lint", "ruff", "test"]

[tasks.lint]
run = 'uv run ty check'

[tasks.ruff]
run = 'uv run ruff check'

[tasks.test]
run = 'uv run pytest'

[tasks.coverage]
run = [
    "uv run coverage run --source=homepage --omit=homepage/__main__.py,homepage/cli.py -m pytest",
    "uv run coveralls",
]
