[tool.poetry]
name = "homepage"
version = "0.0.3"
description = "Home Page"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.scripts]
"homepage" = "homepage.__main__:cli"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.2"
fastapi = "^0.112.0"
Jinja2 = "^3.1.4"
loguru = "^0.7.2"
prometheus-fastapi-instrumentator = "^7.0.0"
pydantic-settings = "^2.4.0"
questionary = "^2.0.1"
click = "^8.1.7"
validators = "^0.33.0"

[tool.poetry.dependencies.uvicorn]
extras = ["standard"]
version = "^0.30.5"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
mypy = "^1.11"
pylint-pydantic = "^0.3.2"
requests = "^2.32.3"
httpx = "^0.27.0"
ruff = "^0.6.0"
types-click = "^7.1.8"

[tool.pylint.MASTER]
max-line-length = 200
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "homepage"
description = "Home Page"
license = "MIT"
authors = [{ name = "James Hogkinson", email = "james@terminaloutcomes.com" }]
