[tool.poetry]
name = "homepage"
version = "0.0.3"
description = "Home Page"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.scripts]
"homepage" = "homepage.__main__:cli"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.6"
fastapi = "^0.115.8"
Jinja2 = "^3.1.5"
loguru = "^0.7.3"
prometheus-fastapi-instrumentator = "^7.0.2"
pydantic-settings = "^2.8.0"
questionary = "^2.1.0"
click = "^8.1.8"
validators = "^0.34.0"
requests = "^2.32.3"
pytest-cov = "^6.0.0"

[tool.poetry.dependencies.uvicorn]
extras = ["standard"]
version = "^0.34.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
mypy = "^1.15"
pylint-pydantic = "^0.3.5"
httpx = "^0.28.1"
ruff = "^0.9.9"
types-click = "^7.1.8"
types-requests = "^2.32.0.20241016"

[tool.pylint.MASTER]
max-line-length = 200
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "homepage"
description = "Home Page"
license = "MIT"
authors = [{ name = "James Hogkinson", email = "james@terminaloutcomes.com" }]
