[tool.poetry]
name = "homepage"
version = "0.0.3"
description = "Home Page"
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.scripts]
"homepage" = "homepage.__main__:cli"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.5.2"
fastapi = "^0.104.1"
Jinja2 = "^3.1.2"
loguru = "^0.7.2"
prometheus-fastapi-instrumentator = "^6.1.0"
pydantic-settings = "^2.1.0"
questionary = "^2.0.1"
click = "^8.1.7"
validators = "^0.22.0"

[tool.poetry.dependencies.uvicorn]
extras = [
    "standard",
]
version = "^0.24.0"

[tool.poetry.dev-dependencies]
pylint = "^3.0.3"
pytest = "^7.4.3"
mypy = "^1.7"
black = "^23.12.0"
pylint-pydantic = "^0.3.1"
requests = "^2.31.0"
httpx = "^0.25.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.7"
types-click = "^7.1.8"

[tool.pylint.MASTER]
max-line-length = 200
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "homepage"
description = "Home Page"
license = "MIT"
authors = [
    { name = "James Hogkinson", email = "james@terminaloutcomes.com" },
]
