[tool.poetry]
name = "homepage"
version = "0.0.1"
description = "Home Page"
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.scripts]
"homepage" = "homepage.__main__:cli"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.2"
fastapi = "^0.81.0"
click = "^8.1.3"
Jinja2 = "^3.1.2"
loguru = "^0.6.0"
prometheus-fastapi-instrumentator = "^5.9.1"

[tool.poetry.dependencies.uvicorn]
extras = [
    "standard",
]
version = "^0.18.2"

[tool.poetry.dev-dependencies]
pylint = "^2.15.2"
pytest = "^7.1.3"
mypy = "^0.971"
black = "^22.8.0"
bandit = "^1.7.4"
pylint-pydantic = "^0.1.4"
requests = "^2.28.1"

[tool.pylint.MASTER]
max-line-length = 200
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "homepage"
description = "Home Page"
license = "MIT"
version = "0.0.1"
authors = [
    { name = "James Hogkinson", email = "james@terminaloutcomes.com" },
]
