[tool.poetry]
name = "homepage"
version = "0.0.3"
description = "Home Page"
authors = [
    "James Hogkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.scripts]
"homepage" = "homepage.__main__:cli"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.7"
fastapi = "^0.95.1"
click = "^8.1.3"
Jinja2 = "^3.1.2"
loguru = "^0.7.0"
prometheus-fastapi-instrumentator = "^6.0.0"

[tool.poetry.dependencies.uvicorn]
extras = [
    "standard",
]
version = "^0.22.0"

[tool.poetry.dev-dependencies]
pylint = "^2.17.3"
pytest = "^7.3.1"
mypy = "^1.2"
black = "^23.3.0"
bandit = "^1.7.5"
pylint-pydantic = "^0.1.8"
requests = "^2.29.0"
httpx = "^0.24.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.263"

[tool.pylint.MASTER]
max-line-length = 200
extension-pkg-whitelist = "pydantic"
load-plugins = "pylint_pydantic"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "homepage"
description = "Home Page"
license = "MIT"
authors = [
    { name = "James Hogkinson", email = "james@terminaloutcomes.com" },
]
