---
name: pytest

"on":
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - name: Running pytest
        run: |
          mise run test
